Project1/Controllers/DetailSongController.cs
using Microsoft.AspNetCore.Mvc;
using Project1.Context;
using Project1.Dtos;
using Project1.Interfaces;

namespace Project1.Controllers
{

    public class DetailSongController : Controller
    {

        private readonly IReadOnlySongService _readOnlySongService;
        private readonly IReadOnlyCategoryService _readOnlyCategoryService;
        private readonly IAddableSongSerivce _addableSongService;

        private readonly ProjectDbContext _db;

        public DetailSongController(
            IReadOnlySongService readOnlySongService,
            IReadOnlyCategoryService readOnlyCategoryService,
            IAddableSongSerivce addableSongSerivce,
            ProjectDbContext db)
        {
            _readOnlySongService = readOnlySongService;
            _readOnlyCategoryService = readOnlyCategoryService; 
            _addableSongService = addableSongSerivce;
            _db = db;
        }

        [HttpGet()]
        public IActionResult Details(int Id)
        {
            SongDto songDto = _readOnlySongService
                .GetById(Id);

            return View("Index", songDto);
        }




    }
}

Project1/Controllers/SongListController.cs
using Microsoft.AspNetCore.Mvc;
using Project1.Context;
using Project1.Dtos;
using Project1.Interfaces;
using Project1.Models;
using System.Diagnostics;

namespace Project1.Controllers
{
    public class SongListController : Controller
    {

        private readonly IReadOnlySongService _readOnlySongService;
        private readonly ProjectDbContext _db;

        public SongListController(
            IReadOnlySongService readOnlySongService,
            IReadOnlyCategoryService readOnlyCategoryService,
            ProjectDbContext db)
        {
            _readOnlySongService = readOnlySongService;
            _db = db;
        }

        [HttpGet()]
        public IActionResult Index()
        {
            IEnumerable<SongDto> model = _readOnlySongService
                .Load()
                .GetData();


            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Project1/Views/DetailSong/Index.cshtml
@using Project1.Dtos;
@model SongDto;

@{
    ViewData["Title"] = "Detail page of Song";
}

<div style="display:flex; flex-direction: column">
    <div>
        <a class="nav-link text-dark" asp-area="" asp-controller="SongList" asp-action="Index">Back to all songs</a>
    </div>
 </div>

<h1>Song information</h1>

<div class="row">
    <div class="col-md-4">
        <form>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input disabled asp-for="Title" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input disabled asp-for="Artist" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input disabled asp-for="Album" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input disabled asp-for="Duration" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ReleaseYear" class="control-label"></label>
                <input disabled asp-for="ReleaseYear" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input disabled asp-for="CategoryName" class="form-control" />
            </div>
        </form>
    </div>
</div>