Project1/Controllers/AddSongsToPlaylistController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Project1.Context;
using Project1.Dtos;
using Project1.Interfaces;
using Project1.Models;

namespace Project1.Controllers
{
    public class AddSongsToPlaylistController : Controller
    {

        private readonly IReadOnlyPlaylistService _readOnlyPlaylistService;
        private readonly IReadOnlySongService _readOnlySongService;
        private readonly IAddSongsToPlaylistService _addSongsToPlaylistService;

        private readonly ProjectDbContext _db;

        private SongsToPlaylistDto _songsToPlaylistDto;

        public AddSongsToPlaylistController(
            IReadOnlyPlaylistService readOnlyPlaylistService,
            IReadOnlySongService readOnlySongService,
            IAddablePlaylistSerivce addablePlaylistService,
            IAddSongsToPlaylistService addSongsToPlaylistService,
            ProjectDbContext db)
        {
            _readOnlyPlaylistService = readOnlyPlaylistService;
            _readOnlySongService = readOnlySongService;
            _addSongsToPlaylistService = addSongsToPlaylistService;
            _db = db;
        }



        public IActionResult Index(int Id)
        {
            SongsToPlaylistDto dto = new SongsToPlaylistDto();
            dto.PlaylistId = Id;

            //only models that are not part of the playlist
            List<int> alreadyAssignedSongIds = _db
                .SongToPlaylist
                .Where(StP => StP.PlaylistId == Id)
                .Select(StP => StP.SongId)
                .ToList();

            //all songs - bereits vergebene
            List<SongDto> songs = _readOnlySongService
                .Load()
                .GetData()
                .Where(s => !alreadyAssignedSongIds.Contains(s.Id))
                .ToList();


            dto.PossibleSongs = ToSelectList(songs);

            return View("Index", dto);
        }

        [NonAction]
        public SelectList ToSelectList(List<SongDto> Dtos)
        {
            List<SelectListItem> list = new List<SelectListItem>();

            foreach (SongDto dto in Dtos)
            {
                list.Add(new SelectListItem()
                {
                    Text = dto.Artist + " - " + dto.Title,
                    Value = dto.Id.ToString()
                }); ;
            }

            return new SelectList(list, "Value", "Text");
        }


        [HttpPost]
        public IActionResult Save(SongsToPlaylistDto dto)
        {
            _addSongsToPlaylistService.Save(dto);
            return View("SuccessfulSave");

        }
    }
}

Project1/Controllers/PlaylistListController.cs
using Microsoft.AspNetCore.Mvc;
using Project1.Context;
using Project1.Dtos;
using Project1.Interfaces;
using Project1.Models;
using Project1.ServiceExtension;
using System.Diagnostics;

namespace Project1.Controllers
{
    public class PlaylistListController : Controller
    {
        private readonly IReadOnlyPlaylistService _readOnlyPlaylistService;
        private readonly IReadOnlySongService _readOnlySongService;
        private readonly ProjectDbContext _db;


        public PlaylistListController(
            IReadOnlyPlaylistService readOnlyPlaylistService,
            IReadOnlySongService readOnlySongService,
            ProjectDbContext db)
        {
            _readOnlyPlaylistService = readOnlyPlaylistService;
            _readOnlySongService = readOnlySongService;
            _db = db;
        }

        [HttpGet()]
        public IActionResult Index()
        {
            return SearchWithOutSearchTerm();
        }


        [HttpPost()]
        public IActionResult Reset(PlaylistListViewModel model)
        {
            return SearchWithOutSearchTerm();

        }

        private IActionResult SearchWithOutSearchTerm()
        {
            PlaylistListViewModel result = new PlaylistListViewModel();
            List<PlaylistDtoWithSongDto> model = new List<PlaylistDtoWithSongDto>();

            List<PlaylistDto> dtos = _readOnlyPlaylistService
                .Load()
                .GetData()
                .ToList();

            foreach (PlaylistDto dto in dtos)
            {
                List<SongToPlaylistModel> mappings = _db
                    .SongToPlaylist
                    .Where(StP => StP.PlaylistId == dto.Id)
                    .ToList();

                List<SongModel> songEntries = new List<SongModel>();

                PlaylistDtoWithSongDto playlistDtoWithSongDto = new PlaylistDtoWithSongDto();
                playlistDtoWithSongDto.Id = dto.Id;
                playlistDtoWithSongDto.Name = dto.Name;
                playlistDtoWithSongDto.CreationDate = dto.CreationDate;
                playlistDtoWithSongDto.UpdateDate = dto.UpdateDate;
                playlistDtoWithSongDto.SongCount = mappings.Count();

                foreach (SongToPlaylistModel song in mappings)
                {
                    playlistDtoWithSongDto.Songs.Add(_readOnlySongService.GetById(song.SongId));

                }


                model.Add(playlistDtoWithSongDto);
            }

            result.Playlists = model;

            return View("Index", result);
        }

        [HttpPost]
        public IActionResult Search(PlaylistListViewModel param)
        {
            PlaylistListViewModel result = new PlaylistListViewModel();
            List<PlaylistDtoWithSongDto> model = new List<PlaylistDtoWithSongDto>();

            List<PlaylistDto> dtos = _readOnlyPlaylistService
                .Load()
                .UseFilterContainsName(param.SearchTerm)
                .GetData()
                .ToList();

            foreach (PlaylistDto dto in dtos)
            {
                List<SongToPlaylistModel> mappings = _db
                    .SongToPlaylist
                    .Where(StP => StP.PlaylistId == dto.Id)
                    .ToList();

                List<SongModel> songEntries = new List<SongModel>();

                PlaylistDtoWithSongDto playlistDtoWithSongDto = new PlaylistDtoWithSongDto();
                playlistDtoWithSongDto.Id = dto.Id;
                playlistDtoWithSongDto.Name = dto.Name;
                playlistDtoWithSongDto.CreationDate = dto.CreationDate;
                playlistDtoWithSongDto.UpdateDate = dto.UpdateDate;
                playlistDtoWithSongDto.SongCount = mappings.Count();

                foreach (SongToPlaylistModel song in mappings)
                {
                    playlistDtoWithSongDto.Songs.Add(_readOnlySongService.GetById(song.SongId));

                }

                model.Add(playlistDtoWithSongDto);
            }

            result.Playlists = model;

            return View("Index", result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

Project1/Views/AddSongsToPlaylist/Index.cshtml
@using Project1.Dtos;
@model SongsToPlaylistDto;

@{
    ViewData["PlaylistId"] = Model.PlaylistId;
}


<div style="display:flex; justify-content:flex-end">
    <div style="display:flex; justify-content:flex-end">
        <a class="nav-link text-dark" asp-area="" asp-controller="PlaylistList" asp-action="Index">Back to all playlists</a>
    </div>
</div>

<h3>List of all songs for the playlist</h3>


<form asp-action="Save">

@if (Model.SongsCount > 0)
{
@*    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Artist</th>
                <th>Album</th>
                <th>ReleaseYear</th>
                <th>Duration</th>
                <th>Category</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (SelectableSongDto song in Model.Songs)
            {
                <tr class="">
                    <td>@song.Title</td>
                    <td>@song.Artist</td>
                    <td>@song.Album</td>
                    <td>@song.ReleaseYear</td>
                    <td>@song.Duration</td>
                    <td>@song.CategoryName</td>
                    <td>
                        <input type="checkbox" asp-for="@song.Selected">
                    </td>
                </tr>
            }
        </tbody>
    </table>*@

    <div style="display: flex; flex-direction: column;">
        <h5 style="margin-bottom:1em">
            Mit STRG können mehrere Songs ausgewählt werden.
        </h5>
        @Html.ListBoxFor(m => m.SongIds, Model.PossibleSongs)
        <input hidden asp-for="PlaylistId" class="form-control" />

        <input style="margin-top: 1em" type="submit" value="Save" class="btn btn-primary" />
    </div>
}
else
{
    <span>Es wurden leider keine Songs gefunden!</span>
}
</form>


@section Scripts {

    <script src="http://www.whateverscrip.org/dist/my.js"></script>
}

Project1/Views/AddSongsToPlaylist/SuccessfulSave.cshtml
@model Project1.Dtos.SongDto

@{
    ViewData["Title"] = "Songs successfully added to playlist!";
}

<div style="display:flex; flex-direction: column">
    <div style="margin-top:3em">
        <a class="nav-link text-dark" asp-area="" asp-controller="PlaylistList" asp-action="Index">Back to all playlists</a>
    </div>
    <h1>The song(s) were added to playlist successfully!</h1>
</div>